development:
  adapter: mysql
  encoding: utf8
  database: presentah
  username: root
  password: pwd
  host: localhost
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql
  encoding: utf8
  database: presentah_test
  username: root
  password: pwd
  host: localhost
  socket: /var/run/mysqld/mysqld.sock

staging:
  development
production:
  development

